### ISSUE TITLE
Type error when parsing HTML

### ISSUE THREAD

**Issue by libre-man** [copyleft/cl-html5-parser#17]
I sometimes get a parse error when parsing html. The error originates from `HTML5-STREAM-CHARS-UNTIL` and it is that `CHUNK` is not of type `CHUNK`. A example HTML which triggers this bug can be found [here](https://www.refheap.com/9ae5c6d72d91d6a1797cfe9e4).

**Comment by bakketun** [comment]
I don't get this error with SBCL 1.3.11. Which implementation are you using?

**Comment by libre-man** [comment]
I'm running with SBCL 1.3.12 and using `:cxml` as the `:dom` type.

**Comment by libre-man** [comment]
I updated my quicklisp and upgraded to SBCL 1.3.15 and the errors seem to have disappeared. So I think it as an error on my part. Sorry for the noise.

**Comment by bakketun** [comment]
It might have been related to the bug fixed in pull request https://github.com/copyleft/cl-html5-parser/pull/16. I have merged that now.
