### ISSUE TITLE
XML namespace and transformation to CXML error

### ISSUE THREAD

**Issue by Ferada** [copyleft/cl-html5-parser#22]
This rather minimal example fails when creating a CXML DOM from it:

    (html5-parser:parse-html5 "<html lang=\"en\" xml:lang=\"en\"></html>" :dom :cxml)
    ; => NAMESPACE_ERR (14): prefix specified but no namespace URI

That is, `xml:lang` is given to CXML but without having the `xml` namespace specified, if I understand that correctly.

I've patched `%START-TAG-HTML` to include a `ADJUST-FOREIGN-ATTRIBUTES` call, which looks like it does *the right thing* at a glance, but I'm very skeptical whether that's actually correct:

    (defmethod %start-tag-html (*phase* token)
      (with-slots (first-start-tag open-elements)
          *parser*
        (when (and (not first-start-tag)
                   (string= (getf token :name) "html"))
          (parser-parse-error :non-html-root))
        ;; XXX Need a check here to see if the first start tag token emitted is
        ;; this token... If it's not, invoke self.parser.parseError().
        (let ((root-element (first open-elements)))
          (adjust-foreign-attributes token)
          (loop for (name . value) in (getf token :data)
                do (let ((namespace (if (stringp name) NIL (third name)))
                         (name (if (stringp name) name (second name))))
                     (unless (element-attribute root-element name namespace)
                       (setf (element-attribute root-element name namespace) value)))))
        (setf first-start-tag nil)
        nil))

With that definition in place, the resulting DOM has two attributes on the `html` node, one `lang`/`en` without a namespace, one `lang`/`en` with the `http://www.w3.org/XML/1998/namespace` namespace, which looks sensible to me.

I especially think this isn't enough since it only handles one specific instance of this pattern, if e.g. some custom embedded namespace is defined (I found one with a referenced RDF schema), still isn't handled, e.g.:

    (html5-parser:parse-html5 "<html xmlns:v=\"http://rdf.data-vocabulary.org/#\"></html>" :dom :cxml)

**Comment by bakketun** [comment]
I have committed some improvement. The solution might seem wrong though, but this is because HTML5 syntax does not support namespaces.

```lisp
(html5-parser:parse-html5 "<html lang=\"en\" xml:lang=\"en\" xmlns:v=\"http://rdf.data-vocabulary.org/#\"></html>" :dom :cxml)
```
This results in three attributes of the `html` element with names `lang`, `xml:lang` and `xmlns:v`. None of the attributes have a namespace uri or prefix. The colon is simply part of the name. Only the `lang` attribute is defined in HTML5.

The only way an attribute can get into a namespace is via `ADJUST-FOREIGN-ATTRIBUTES`, but this only applies to SVG and MathML elements.

I am considering to escape colons (and any other invalid characters) in tag names when converting to XML. Section [8.2.7 Coercing an HTML DOM into an infoset](https://www.w3.org/TR/html5/syntax.html#coercing-an-html-dom-into-an-infoset) defines how to do this. This will convert `xml:lang` to `xmlU00003Alang`.

**Comment by Ferada** [comment]
Awesome, thanks already.

Strictly speaking yes, looking at http://w3c.github.io/html/dom.html#the-lang-and-xmllang-attributes that seems to be acceptable though for `xml:lang` at least.

In any case my real-life problem is that this parser is the best option for actual HTML files in the wild; I don't care too strongly about representing it accurately as XML, except that mapping it to CXML is *very* convenient to be able to use XPath on it! N.b. I'm also writing some compatibility handlers that will run PLEXIPPUS-XPATH directly on the CL-HTML5-PARSER DOM, but that'll still have to do the same thing.

Frankly none of the files in the wild will pass a strict XHTML parser either; for all I care there could be a switch to strip this all out, or a custom handler maybe? Just rejecting it all completely when encountering these tags isn't so great IMO.

**Comment by bakketun** [comment]
I've implemented escaping of names when converting to XML now. See README.md for some examples how this works.

The `xml:lang` attribute on HTML elements should be ignored by applications. It only allowed to for backwards comparability to allow HTML like this to validate: `<html lang='en' xml:lang='en'>`.

I might retry the experiment in the cxml-dom branch, but I will prioritize to get test for the CXML conversion step first and look at the encoding issues (#7 and #22).
